from .prompts import CALCULATOR_TEMPLATE, DEFAULT_TEMPLATE
from .prompts import OPENAI_PLANNER_TEMPLATE, OPENAI_THOUGHT_TEMPLATE, OPENAI_OBSERVATION_TEMPLATE, \
    OPENAI_ANALYZE_MEMORY_TEMPLATE
from .prompts import ZEPHYR_STANDARD_TEMPLATE
